//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using MongoDB.Bson;
    using MongoDB.Bson.Serialization.Attributes;
    using System;
    using System.Collections.Generic;
    
    public partial class ChildInFamily
    {
        public ChildInFamily()
        {
        }
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string ChildInFamilyId { get; set; }
        public string Name { get; set; }
        public string FamilyId { get; set; }
    }
}
