//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using MongoDB.Bson;
    using MongoDB.Bson.Serialization.Attributes;
    using System;
    using System.Collections.Generic;

    public partial class Frequency
    {
        public Frequency()
        {
        }
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string FrequencyId { get; set; }
        public string FrequencyType { get; set; }


    }
}
