//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstablishmentForChild
    {
        public int EstablishmentForChildId { get; set; }
        public Nullable<int> EstablishmentId { get; set; }
        public Nullable<int> ChildId { get; set; }
    
        public virtual ChildInFamily ChildInFamily { get; set; }
        public virtual Establishments Establishments { get; set; }
    }
}
