//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerInTransportation
    {
        public int PassengerInTransportationId { get; set; }
        public Nullable<int> TransportationId { get; set; }
        public Nullable<int> PassengerId { get; set; }
    
        public virtual ChildInFamily ChildInFamily { get; set; }
        public virtual Transportation Transportation { get; set; }
    }
}
