//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationInTrack
    {
        public int StationInTrackId { get; set; }
        public Nullable<int> TrackId { get; set; }
        public Nullable<int> StationId { get; set; }
        public Nullable<int> OrdinalNumberInTrack { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Track Track { get; set; }
    }
}
