//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.StationInTrack = new HashSet<StationInTrack>();
        }
    
        public int TrackId { get; set; }
        public Nullable<int> EstablishmentId { get; set; }
        public string Destination_Source { get; set; }
        public string Ingathering_Interspersion { get; set; }
        public Nullable<int> FrequencyId { get; set; }
        public Nullable<int> TrackPrice { get; set; }
    
        public virtual Establishments Establishments { get; set; }
        public virtual Frequency Frequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationInTrack> StationInTrack { get; set; }
    }
}
