//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transportation()
        {
            this.ActualTransportation = new HashSet<ActualTransportation>();
            this.PassengerInTransportation = new HashSet<PassengerInTransportation>();
        }
    
        public int TransportationId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string SourceAddress { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> VehicleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActualTransportation> ActualTransportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerInTransportation> PassengerInTransportation { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
